# Generated by Django 4.2.13 on 2024-06-24 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_approved_user_is_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_guest',
        ),
    ]
