# Generated by Django 4.2.13 on 2024-06-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_options_alter_enrollment_options_and_more'),
        ('subjects', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='instructor',
        ),
        migrations.AddField(
            model_name='subject',
            name='courses',
            field=models.ManyToManyField(related_name='subjects', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
